console.log("Success")
/*
document.write('');
document.write('<body style="background-color: #e9ecef;">');
document.write('');
document.write('  <!-- start preheader -->');
document.write('  <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">');
document.write('    A preheader is the short summary text that follows the subject line when an email is viewed in the inbox.');
document.write('  </div>');
document.write('  <!-- end preheader -->');
document.write('');
document.write('  <!-- start body -->');
document.write('  <table border="0" cellpadding="0" cellspacing="0" width="100%">');
document.write('');
document.write('    <!-- start logo -->');
document.write('    <tr>');
document.write('      <td align="center" bgcolor="#e9ecef">');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">');
document.write('        <tr>');
document.write('        <td align="center" valign="top" width="600">');
document.write('        <![endif]-->');
document.write('        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">');
document.write('          <tr>');
document.write('            <td align="center" valign="top" style="padding: 36px 24px;">');
document.write('              <a href="https://sendgrid.com" target="_blank" style="display: inline-block;">');
document.write('                <img src="./img/paste-logo-light@2x.png" alt="Logo" border="0" width="48" style="display: block; width: 48px; max-width: 48px; min-width: 48px;">');
document.write('              </a>');
document.write('            </td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        </td>');
document.write('        </tr>');
document.write('        </table>');
document.write('        <![endif]-->');
document.write('      </td>');
document.write('    </tr>');
document.write('    <!-- end logo -->');
document.write('');
document.write('    <!-- start hero -->');
document.write('    <tr>');
document.write('      <td align="center" bgcolor="#e9ecef">');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">');
document.write('        <tr>');
document.write('        <td align="center" valign="top" width="600">');
document.write('        <![endif]-->');
document.write('        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">');
document.write('          <tr>');
document.write('            <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">');
document.write('              <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">Confirm Your Email Address</h1>');
document.write('            </td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        </td>');
document.write('        </tr>');
document.write('        </table>');
document.write('        <![endif]-->');
document.write('      </td>');
document.write('    </tr>');
document.write('    <!-- end hero -->');
document.write('');
document.write('    <!-- start copy block -->');
document.write('    <tr>');
document.write('      <td align="center" bgcolor="#e9ecef">');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">');
document.write('        <tr>');
document.write('        <td align="center" valign="top" width="600">');
document.write('        <![endif]-->');
document.write('        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">');
document.write('');
document.write('          <!-- start copy -->');
document.write('          <tr>');
document.write('            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">');
document.write('              <p style="margin: 0;">Tap the button below to confirm your email address. If you didn\'t create an account with <a href="https://sendgrid.com">Paste</a>, you can safely delete this email.</p>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end copy -->');
document.write('');
document.write('          <!-- start button -->');
document.write('          <tr>');
document.write('            <td align="left" bgcolor="#ffffff">');
document.write('              <table border="0" cellpadding="0" cellspacing="0" width="100%">');
document.write('                <tr>');
document.write('                  <td align="center" bgcolor="#ffffff" style="padding: 12px;">');
document.write('                    <table border="0" cellpadding="0" cellspacing="0">');
document.write('                      <tr>');
document.write('                        <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">');
document.write('                          <a href="https://sendgrid.com" target="_blank" style="display: inline-block; padding: 16px 36px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px;">Do Something Sweet</a>');
document.write('                        </td>');
document.write('                      </tr>');
document.write('                    </table>');
document.write('                  </td>');
document.write('                </tr>');
document.write('              </table>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end button -->');
document.write('');
document.write('          <!-- start copy -->');
document.write('          <tr>');
document.write('            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">');
document.write('              <p style="margin: 0;">If that doesn\'t work, copy and paste the following link in your browser:</p>');
document.write('              <p style="margin: 0;"><a href="https://sendgrid.com" target="_blank">https://same-link-as-button.url/xxx-xxx-xxxx</a></p>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end copy -->');
document.write('');
document.write('          <!-- start copy -->');
document.write('          <tr>');
document.write('            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf">');
document.write('              <p style="margin: 0;">Cheers,<br> Paste</p>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end copy -->');
document.write('');
document.write('        </table>');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        </td>');
document.write('        </tr>');
document.write('        </table>');
document.write('        <![endif]-->');
document.write('      </td>');
document.write('    </tr>');
document.write('    <!-- end copy block -->');
document.write('');
document.write('    <!-- start footer -->');
document.write('    <tr>');
document.write('      <td align="center" bgcolor="#e9ecef" style="padding: 24px;">');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">');
document.write('        <tr>');
document.write('        <td align="center" valign="top" width="600">');
document.write('        <![endif]-->');
document.write('        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">');
document.write('');
document.write('          <!-- start permission -->');
document.write('          <tr>');
document.write('            <td align="center" bgcolor="#e9ecef" style="padding: 12px 24px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">');
document.write('              <p style="margin: 0;">You received this email because we received a request for [type_of_action] for your account. If you didn\'t request [type_of_action] you can safely delete this email.</p>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end permission -->');
document.write('');
document.write('          <!-- start unsubscribe -->');
document.write('          <tr>');
document.write('            <td align="center" bgcolor="#e9ecef" style="padding: 12px 24px; font-family: \'Source Sans Pro\', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">');
document.write('              <p style="margin: 0;">To stop receiving these emails, you can <a href="https://sendgrid.com" target="_blank">unsubscribe</a> at any time.</p>');
document.write('              <p style="margin: 0;">Paste 1234 S. Broadway St. City, State 12345</p>');
document.write('            </td>');
document.write('          </tr>');
document.write('          <!-- end unsubscribe -->');
document.write('');
document.write('        </table>');
document.write('        <!--[if (gte mso 9)|(IE)]>');
document.write('        </td>');
document.write('        </tr>');
document.write('        </table>');
document.write('        <![endif]-->');
document.write('      </td>');
document.write('    </tr>');
document.write('    <!-- end footer -->');
document.write('');
document.write('  </table>');
document.write('  <!-- end body -->');
document.write('');

*/
document.write('<div class="d-flex justify-content-center align-items-center container">');
document.write('        <div class="card py-5 px-3">');
document.write('            <h5 class="m-0">Mobile phone verification</h5><span class="mobile-text">Enter the code we just send on your mobile phone <b class="text-danger">+91 86684833</b></span>');
document.write('            <div class="d-flex flex-row mt-5"><input type="text" class="form-control" autofocus=""><input type="text" class="form-control"><input type="text" class="form-control"><input type="text" class="form-control"></div>');
document.write('            <div class="text-center mt-5"><span class="d-block mobile-text">Don\'t receive the code?</span><span class="font-weight-bold text-danger cursor">Resend</span></div>');
document.write('        </div>');
document.write('    </div>');


